version: '3'

tasks:
  verify:
    aliases:
      - v
    cmds:
      - dafny verify dfyconfig.toml {{.CLI_ARGS}}


  verify-logged-insertion-sort:
    cmds:
      - dafny verify --standard-libraries --cores 100% --log-format text src/InsertionSort.dfy > logs/InsertionSort.txt

  # measure-complexity-insertion-sort:
  #   cmds:
  #     - dafny measure-complexity src/InsertionSort.dfy --log-format csv --mutations 10 --standard-libraries

  translate-rs:
    cmds:
      - dafny translate rs dfyconfig.toml
